name: DanSMP
version: 1.0
api-version: 1.13
main: io.github.arleycht.SMP.DanSMP
depend: [ProtocolLib]
commands:
  dansmp:
    description: DanSMP command
    usage: /<command>
    persmission: dansmp.dansmp
