name: DanSMP
version: 1.0
api-version: 1.13
main: io.github.arleycht.SMP.DanSMP
#loadbefore:
#  - ProtocolLib
#depend:
#  - ProtocolLib
commands:
  dansmp:
    description: The DanSMP command
    usage: /<command> [list|give <artifact>]
    persmission: dansmp
permissions:
  dansmp.*:
    default: op
    children:
      dansmp.eject: true
  dansmp.eject:
    description: Ejects command user from any vehicle
    default: not op
  dansmp.artifact.*:
    children:
      dansmp.artifact.list: true
      dansmp.artifact.give: true
  dansmp.artifact.list:
    description: Lists all available artifacts
    default: not op
  dansmp.artifact.give:
    description: Gives artifacts
    default: op
